[phases.setup]
nixPkgs = ["python312", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput"]

# Don't run migrations during build - they need database access at runtime
[phases.release]

[start]
cmd = "python manage.py migrate && gunicorn crm_project.wsgi:application --bind 0.0.0.0:$PORT"
