# Generated by Django 5.2.7 on 2025-10-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='milestone',
            field=models.CharField(choices=[('not_contacted', 'Not yet contacted'), ('first_call', 'First Call'), ('not_interested', 'Not interested'), ('email_sent', 'Email sent'), ('meeting_arranged', 'Meeting arranged'), ('waiting_on_contact', 'Waiting on Contact'), ('successful', 'Successful')], default='not_contacted', help_text='Current stage in the lead journey', max_length=50),
        ),
    ]
