# Generated by Django 5.2.7 on 2025-10-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_milestone'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(blank=True, help_text='Primary contact person for this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_companies', to='contacts.contact'),
        ),
    ]
